stages:
  - build
  - test
  - deploy
  - deploy_ansible

build_app:
  stage: build 
  image: golang:1.16.15
  script:
    - go build
  artifacts:
    paths:
      - pig
      - /cmd
      - /internal
      - /resources

build_docker:
  stage: build
  image: docker
  before_script:
    - export
    - docker login stud-gitlab.innoca.local:5005 -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}

  services:
    - name: docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

test_app:
  stage: test
  image: golang:1.16.15
  script:
    - go test ./...

deploy:
  stage: deploy
  image: alpine/k8s:1.25.14
  before_script:
    - export KUBECONFIG=$k8s_config
  script:
    - helm upgrade pig ./k8s-manifests/pig --install --values=./k8s-manifests/pig/values.yaml
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always

deploy_ansible:
   stage: deploy_ansible  
   dependencies:
    - build_app
   image: alpine/ansible
   before_script:
   - mkdir secret
   - echo "$ansible_ssh" > secret/ansible.key
   - chmod 400 secret/ansible.key
   - export ANSIBLE_HOST_KEY_CHECKING=False
   script:
     - ansible-playbook ansible/playbook.yml --private-key secret/ansible.key --user student --inventory ansible/inventory
   rules:
     - if: $CI_COMMIT_BRANCH == 'main'
       when: always        