apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig
  labels:
    app: pig
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pig
  template:
    metadata:
      labels:
        app: pig
    spec:
      containers:
      - name: pig
        image: sion2k/pig:t1-k8s
        ports:
        - containerPort: 8000